# This is a basic workflow to help you get started with Actions

name: AUTO_CONTENT
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  EXTRACTION:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      # Runs a single command using the runners shell
      - name: Get Repo
        uses: actions/checkout@v2
    
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            bbc_content.db
          key: ${{ runner.os }}-node-${{ hashFiles('**/bbc_content.db') }}
