# This is a basic workflow to help you get started with Actions

name: AUTO_CONTENT
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  EXTRACTION:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      # Runs a single command using the runners shell
      - name: Get Repo
        uses: actions/checkout@v2
    
      - uses: 'actions/setup-python@v2'
        with:
          # CAUTION: Replace this hardcoded "3.9" string with the
          # major and minor version of your desired Python interpreter.
          python-version: "3.9"
      - uses: 'actions/cache@v2'
        id: cache
        with:
        # CAUTION: Replace this hardcoded "python3.9" dirname with
        # the dirname providing your desired Python interpreter.
         path: |
           ${{ env.pythonLocation }}/lib/python3.9/site-packages/*
           bbcontent.db
         key: ${{ runner.os }}-pip-${{ hashFiles('**/bbcontent.db') }}
         restore-keys: |
           ${{ runner.os }}-pip-
           ${{ runner.os }}-
     
      - name: Install dependencies
        run: |
           pip3 install --user scrapy
           scrapy --version
